name          'KyleAnderson/redis_sentinel'
version '0.0.9'
source        'https://github.com/solarkennedy/puppet-redis_sentinel'
author        'Kyle Anderson <kyle@xkyle.com>'
license       'Apache License, Version 2.0'
summary       'Configure redis-sentinels'
description   'Configure redis-sentinels'
project_page  'https://github.com/solarkennedy/puppet-redis_sentinel'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/concat'
